"""
Django settings for nursing_center project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
import firebase_admin
from firebase_admin import credentials
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,*.railway.app', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost,http://127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    

    
    'courses',  # Our main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'nursing_center.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'courses.context_processors.bulletin_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'nursing_center.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': config(
        'DATABASE_URL',
        default=f"mysql://{config('DB_USER', default='root')}:{config('DB_PASSWORD', default='')}@{config('DB_HOST', default='localhost')}:{config('DB_PORT', default='3306')}/{config('DB_NAME', default='nursing_center')}",
        cast=dj_database_url.parse
    )
}

# Fix for MySQL options if using MySQL
if DATABASES['default'].get('ENGINE') == 'django.db.backends.mysql':
    DATABASES['default']['OPTIONS'] = {
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        'charset': 'utf8mb4',
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'  # Redirect to home after login
LOGOUT_REDIRECT_URL = '/'  # Redirect to home after logout



# Session settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)


# ─── Firebase Admin SDK ────────────────────────────────────────────────────────
# 1. Try to load from environment variable JSON string (Best for Railway)
FIREBASE_KEY_JSON = config('FIREBASE_SERVICE_ACCOUNT_JSON', default=None)
FIREBASE_PROJECT_ID = config('FIREBASE_PROJECT_ID', default='premier-medical-institute')

if not firebase_admin._apps:
    try:
        if FIREBASE_KEY_JSON:
            import json
            cred_dict = json.loads(FIREBASE_KEY_JSON)
            cred = credentials.Certificate(cred_dict)
            firebase_admin.initialize_app(cred, {'projectId': FIREBASE_PROJECT_ID})
            print("SUCCESS: Firebase initialized from environment JSON!")
        else:
            # 2. Fallback to service account file
            _filename = config('FIREBASE_SERVICE_ACCOUNT_KEY', default='firebase-service-account.json')
            _file_path = BASE_DIR / _filename
            
            if _file_path.exists():
                cred = credentials.Certificate(str(_file_path))
                firebase_admin.initialize_app(cred, {'projectId': FIREBASE_PROJECT_ID})
                os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(_file_path)
                print("SUCCESS: Firebase initialized from service account file!")
            else:
                # 3. Final fallback: Absolute path for specific local dev setups
                _abs_path = Path("C:/xxampp/htdocs/Nursing/firebase-service-account.json")
                if _abs_path.exists():
                    cred = credentials.Certificate(str(_abs_path))
                    firebase_admin.initialize_app(cred, {'projectId': FIREBASE_PROJECT_ID})
                    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(_abs_path)
                    print("SUCCESS: Firebase initialized from absolute path!")
                else:
                    print("WARNING: Firebase not initialized. Service account not found.")
    except Exception as e:
        print(f"FAILED: Firebase Initialization Failed: {e}")

