# Generated by Django 4.2.28 on 2026-02-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Premier Medical And Technical Institute', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Upload a PNG logo', null=True, upload_to='site_config/')),
                ('hero_background', models.ImageField(blank=True, help_text='Background image for homepage hero section', null=True, upload_to='site_config/')),
                ('hero_title', models.CharField(default='Welcome to Premier Medical And Technical Institute', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Professional nursing education and training for aspiring healthcare professionals')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]

