# Generated by Django 4.2.28 on 2026-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='dashboard_background',
            field=models.ImageField(blank=True, help_text='Background image for dashboard header', null=True, upload_to='site_config/'),
        ),
    ]
