# Generated by Django 4.2.28 on 2026-02-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_siteconfiguration_dashboard_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='admin_completed',
            field=models.BooleanField(default=False, help_text='If checked, this module is considered completed for ALL students.', verbose_name='Mark Completed (Admin)'),
        ),
    ]
