# Generated by Django 4.2.28 on 2026-02-04 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_admin_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.module'),
        ),
        migrations.AddField(
            model_name='resource',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.module'),
        ),
    ]
