# Generated by Django 4.2.28 on 2026-02-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order to display')),
            ],
            options={
                'verbose_name': 'Branch Phone Number',
                'verbose_name_plural': 'Branch Phone Numbers',
                'ordering': ['order', 'branch_name'],
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Full Facebook Page URL'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter number with country code (e.g., 88017...)', max_length=20),
        ),
    ]
