# Generated by Django 4.2.28 on 2026-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_branchphone_siteconfiguration_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Main contact phone number', max_length=20),
        ),
    ]
