# Generated by Django 4.2.28 on 2026-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_siteconfiguration_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch Name', max_length=200)),
                ('image', models.ImageField(help_text='Upload branch image', upload_to='branches/')),
                ('phone_number', models.CharField(help_text='Contact Number for this branch', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Branch Address')),
                ('google_map_link', models.URLField(blank=True, help_text='Google Maps Location Link')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='branchphone',
            options={'ordering': ['order', 'branch_name'], 'verbose_name': 'Additional Phone Number', 'verbose_name_plural': 'Additional Phone Numbers'},
        ),
        migrations.AlterField(
            model_name='branchphone',
            name='branch_name',
            field=models.CharField(max_length=100, verbose_name='Label (e.g. Office, Support)'),
        ),
    ]
