# Generated by Django 4.2.28 on 2026-02-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_branch_alter_branchphone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
