# Generated by Django 4.2.28 on 2026-02-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_options_remove_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_weeks',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='12 Weeks', max_length=100),
        ),
    ]
