# Generated by Django 4.2.28 on 2026-02-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_duration_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin must verify this user before they can access the platform'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when admin verified this user', null=True),
        ),
    ]
