# Generated by Django 4.2.28 on 2026-02-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_studentprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses assigned to this student by admin', related_name='enrolled_students', to='courses.course'),
        ),
    ]
