# Generated by Django 4.2.28 on 2026-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_studentprofile_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='module',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_subtitle',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Registration No'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
