# Generated by Django 4.2.28 on 2026-02-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_exam_course_remove_exam_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_title',
        ),
    ]
