# Generated by Django 4.2.28 on 2026-02-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_siteconfiguration_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_description',
            field=models.TextField(blank=True, help_text='Description for the homepage hero section', null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Title for the homepage hero section', max_length=200, null=True),
        ),
    ]
