# Generated by Django 4.2.28 on 2026-02-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_siteconfiguration_hero_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_title',
        ),
    ]
